CALL start-load-data-EQM.cmd ADSL
CALL start-load-data-EQM.cmd AFTEK
CALL start-load-data-EQM.cmd AIDL
CALL start-load-data-EQM.cmd AJPH
CALL start-load-data-EQM.cmd AKLN
CALL start-load-data-EQM.cmd ALBK
CALL start-load-data-EQM.cmd ALCL
CALL start-load-data-EQM.cmd ALMC
CALL start-load-data-EQM.cmd ALST
CALL start-load-data-EQM.cmd ANDBK
CALL start-load-data-EQM.cmd APLL
CALL start-load-data-EQM.cmd APSL
CALL start-load-data-EQM.cmd APTE
CALL start-load-data-EQM.cmd APTTR
CALL start-load-data-EQM.cmd AUBD
CALL start-load-data-EQM.cmd BART
CALL start-load-data-EQM.cmd BFL
CALL start-load-data-EQM.cmd BICN
CALL start-load-data-EQM.cmd BKMAH
CALL start-load-data-EQM.cmd BOB
CALL start-load-data-EQM.cmd BOI
CALL start-load-data-EQM.cmd BVHD
CALL start-load-data-EQM.cmd CADIL
CALL start-load-data-EQM.cmd CIPL
CALL start-load-data-EQM.cmd CMC
CALL start-load-data-EQM.cmd CNRA
CALL start-load-data-EQM.cmd CPIL
CALL start-load-data-EQM.cmd CRBK
CALL start-load-data-EQM.cmd CTUN
CALL start-load-data-EQM.cmd DBPH
CALL start-load-data-EQM.cmd DCBL
CALL start-load-data-EQM.cmd DENA
CALL start-load-data-EQM.cmd DHBN
CALL start-load-data-EQM.cmd DHPH
CALL start-load-data-EQM.cmd DIVI
CALL start-load-data-EQM.cmd ECXS
CALL start-load-data-EQM.cmd EDMR
CALL start-load-data-EQM.cmd EDUCO
CALL start-load-data-EQM.cmd ELDER
CALL start-load-data-EQM.cmd EMER
CALL start-load-data-EQM.cmd EVRON
CALL start-load-data-EQM.cmd FDCL
CALL start-load-data-EQM.cmd FED
CALL start-load-data-EQM.cmd FLFD
CALL start-load-data-EQM.cmd FSRC
CALL start-load-data-EQM.cmd FUJI
CALL start-load-data-EQM.cmd GBTL
CALL start-load-data-EQM.cmd GLPH
CALL start-load-data-EQM.cmd GLXO
CALL start-load-data-EQM.cmd GMSO
CALL start-load-data-EQM.cmd HDBK
CALL start-load-data-EQM.cmd HEMAT
CALL start-load-data-EQM.cmd HOCM
CALL start-load-data-EQM.cmd HOVS
CALL start-load-data-EQM.cmd HTECH
CALL start-load-data-EQM.cmd ICBK
CALL start-load-data-EQM.cmd ICSL
CALL start-load-data-EQM.cmd IDBI
CALL start-load-data-EQM.cmd IFLEX
CALL start-load-data-EQM.cmd IIDF
CALL start-load-data-EQM.cmd IINFO
CALL start-load-data-EQM.cmd INDBK
CALL start-load-data-EQM.cmd INDIN
CALL start-load-data-EQM.cmd IOB
CALL start-load-data-EQM.cmd IPLB
CALL start-load-data-EQM.cmd JBCH
CALL start-load-data-EQM.cmd JKBK
CALL start-load-data-EQM.cmd JUBOL
CALL start-load-data-EQM.cmd KARUR
CALL start-load-data-EQM.cmd KBANK
CALL start-load-data-EQM.cmd KNOL
CALL start-load-data-EQM.cmd KOTAK
CALL start-load-data-EQM.cmd KPIT
CALL start-load-data-EQM.cmd LOGIX
CALL start-load-data-EQM.cmd LUPL
CALL start-load-data-EQM.cmd MAST
CALL start-load-data-EQM.cmd MIND
CALL start-load-data-EQM.cmd MITH
CALL start-load-data-EQM.cmd NAUKRI
CALL start-load-data-EQM.cmd NCHP
CALL start-load-data-EQM.cmd NIIT
CALL start-load-data-EQM.cmd NIITT
CALL start-load-data-EQM.cmd NTPH
CALL start-load-data-EQM.cmd NUSE
CALL start-load-data-EQM.cmd NVRT
CALL start-load-data-EQM.cmd OBC
CALL start-load-data-EQM.cmd ORCHID
CALL start-load-data-EQM.cmd PANB
CALL start-load-data-EQM.cmd PARA
CALL start-load-data-EQM.cmd PERSL
CALL start-load-data-EQM.cmd PFIZ
CALL start-load-data-EQM.cmd PLLB
CALL start-load-data-EQM.cmd PLPL
CALL start-load-data-EQM.cmd PLRS
CALL start-load-data-EQM.cmd PNB
CALL start-load-data-EQM.cmd PRTH
CALL start-load-data-EQM.cmd PSB
CALL start-load-data-EQM.cmd RANB
CALL start-load-data-EQM.cmd REDY
CALL start-load-data-EQM.cmd ROLT
CALL start-load-data-EQM.cmd SASK
CALL start-load-data-EQM.cmd SBI
CALL start-load-data-EQM.cmd SHSCH
CALL start-load-data-EQM.cmd SIBK
CALL start-load-data-EQM.cmd SSOW
CALL start-load-data-EQM.cmd STEA
CALL start-load-data-EQM.cmd SUBEX
CALL start-load-data-EQM.cmd SYBK
CALL start-load-data-EQM.cmd TAKE
CALL start-load-data-EQM.cmd TANSL
CALL start-load-data-EQM.cmd TCS
CALL start-load-data-EQM.cmd TEMH
CALL start-load-data-EQM.cmd THEL
CALL start-load-data-EQM.cmd TTEX
CALL start-load-data-EQM.cmd TULIP
CALL start-load-data-EQM.cmd UNBK
CALL start-load-data-EQM.cmd UTBK
CALL start-load-data-EQM.cmd UTIB
CALL start-load-data-EQM.cmd VAKRA
CALL start-load-data-EQM.cmd VBANK
CALL start-load-data-EQM.cmd VINFY
CALL start-load-data-EQM.cmd VYSY
CALL start-load-data-EQM.cmd WPRO
CALL start-load-data-EQM.cmd WRWDT
CALL start-load-data-EQM.cmd YES
CALL start-load-data-EQM.cmd ZINF
CALL start-load-data-EQM.cmd ZYLOG 