.separator "|"






-- ****************************************************************************
-- Import the PRICE HISTORY DATA
-- ****************************************************************************
DELETE FROM TMP_EQM_PRICE_HISTORY;

.import ../temp/data_SUNP_PH TMP_EQM_PRICE_HISTORY
INSERT INTO EQM_PRICE_HISTORY 
       (PRICE, MARKET_CAP, VOLUME, P_E, P_CF, EPS_TTM, SHARES_OUTSTANDING, PERCENT_CHANGE, PERCENT_CHANGE_WEEK, PERCENT_CHANGE_MONTH, PERCENT_CHANGE_12MONTH, HIGH_52_WEEK,                                                      HIGH_52_LOW)
 SELECT PRICE, MARKET_CAP, VOLUME, P_E, P_CF, EPS_TTM, SHARES_OUTSTANDING, PERCENT_CHANGE, PERCENT_CHANGE_WEEK, PERCENT_CHANGE_MONTH, PERCENT_CHANGE_12MONTH, SUBSTR(LOWHIGH_52_WEEK,INSTR(LOWHIGH_52_WEEK,'/')+1) HIGH_52_WEEK, SUBSTR(LOWHIGH_52_WEEK,1, INSTR( LOWHIGH_52_WEEK,'/')-1) LOW_52_WEEK
   FROM TMP_EQM_PRICE_HISTORY; 

   
   
   
   
   

   
   
-- ****************************************************************************
-- Import the EQUITY SHARE DATA
-- ****************************************************************************
DELETE FROM TMP_EQM_5YEAR_DATA;

.import ../temp/data_SUNP_ES TMP_EQM_5YEAR_DATA

INSERT INTO EQM_EQUITY_SHARE_DATA (HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE)
SELECT HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE
FROM (SELECT DATA_YEAR1 AS HIGH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='High') AS SUNP_1, 
     (SELECT DATA_YEAR1 AS LOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Low') AS SUNP_2, 
     (SELECT DATA_YEAR1 AS SALES_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales per share (Unadj.)') AS SUNP_3, 
     (SELECT DATA_YEAR1 AS EARNINGS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Earnings per share (Unadj.)') AS SUNP_4, 
     (SELECT DATA_YEAR1 AS DILUTED_EARNINGS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Diluted earnings per share') AS SUNP_5, 
     (SELECT DATA_YEAR1 AS CASH_FLOW_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Cash flow per share (Unadj.)') AS SUNP_6, 
     (SELECT DATA_YEAR1 AS DIVIDENDS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividends per share (Unadj.)') AS SUNP_7, 
     (SELECT DATA_YEAR1 AS ADJ_DIVIDENDS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. dividends per share') AS SUNP_8, 
     (SELECT DATA_YEAR1 AS DIVIDEND_YIELD_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend yield (eoy)') AS SUNP_9, 
     (SELECT DATA_YEAR1 AS BOOK_VALUE_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Book value per share (Unadj.)') AS SUNP_10, 
     (SELECT DATA_YEAR1 AS ADJ_BOOK_VALUE_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. book value per share') AS SUNP_11, 
     (SELECT DATA_YEAR1 AS SHARES_OUTSTANDING_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Shares outstanding (eoy)') AS SUNP_12, 
     (SELECT DATA_YEAR1 AS BONUS_RIGHTS_CONVERSIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='BRC') AS SUNP_13, 
     (SELECT DATA_YEAR1 AS PRICE_BY_SALES_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Sales ratio') AS SUNP_14, 
     (SELECT DATA_YEAR1 AS AVG_PE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg P/E ratio') AS SUNP_15, 
     (SELECT DATA_YEAR1 AS PRICE_BY_CASHFLOW_RATIO_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='P/CF ratio (eoy)') AS SUNP_16, 
     (SELECT DATA_YEAR1 AS PRICE_BY_BOOK_VALUE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Book Value ratio') AS SUNP_17, 
     (SELECT DATA_YEAR1 AS DIVIDEND_PAYOUT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend payout') AS SUNP_18, 
     (SELECT DATA_YEAR1 AS AVG_MARKET_CAP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg Mkt Cap') AS SUNP_19, 
     (SELECT DATA_YEAR1 AS NO_OF_EMPLOYEES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='No. of employees') AS SUNP_20, 
     (SELECT DATA_YEAR1 AS TOTAL_WAGES_PER_SALARY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total wages/salary') AS SUNP_21, 
     (SELECT DATA_YEAR1 AS AVG_SALES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. sales/employee') AS SUNP_22, 
     (SELECT DATA_YEAR1 AS AVG_WAGES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. wages/employee') AS SUNP_23, 
     (SELECT DATA_YEAR1 AS AVG_NET_PROFIT_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. net profit/employee') AS SUNP_24;
	 
	 
INSERT INTO EQM_EQUITY_SHARE_DATA (HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE)
SELECT HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE
FROM (SELECT DATA_YEAR2 AS HIGH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='High') AS SUNP_1, 
     (SELECT DATA_YEAR2 AS LOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Low') AS SUNP_2, 
     (SELECT DATA_YEAR2 AS SALES_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales per share (Unadj.)') AS SUNP_3, 
     (SELECT DATA_YEAR2 AS EARNINGS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Earnings per share (Unadj.)') AS SUNP_4, 
     (SELECT DATA_YEAR2 AS DILUTED_EARNINGS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Diluted earnings per share') AS SUNP_5, 
     (SELECT DATA_YEAR2 AS CASH_FLOW_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Cash flow per share (Unadj.)') AS SUNP_6, 
     (SELECT DATA_YEAR2 AS DIVIDENDS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividends per share (Unadj.)') AS SUNP_7, 
     (SELECT DATA_YEAR2 AS ADJ_DIVIDENDS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. dividends per share') AS SUNP_8, 
     (SELECT DATA_YEAR2 AS DIVIDEND_YIELD_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend yield (eoy)') AS SUNP_9, 
     (SELECT DATA_YEAR2 AS BOOK_VALUE_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Book value per share (Unadj.)') AS SUNP_10, 
     (SELECT DATA_YEAR2 AS ADJ_BOOK_VALUE_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. book value per share') AS SUNP_11, 
     (SELECT DATA_YEAR2 AS SHARES_OUTSTANDING_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Shares outstanding (eoy)') AS SUNP_12, 
     (SELECT DATA_YEAR2 AS BONUS_RIGHTS_CONVERSIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='BRC') AS SUNP_13, 
     (SELECT DATA_YEAR2 AS PRICE_BY_SALES_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Sales ratio') AS SUNP_14, 
     (SELECT DATA_YEAR2 AS AVG_PE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg P/E ratio') AS SUNP_15, 
     (SELECT DATA_YEAR2 AS PRICE_BY_CASHFLOW_RATIO_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='P/CF ratio (eoy)') AS SUNP_16, 
     (SELECT DATA_YEAR2 AS PRICE_BY_BOOK_VALUE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Book Value ratio') AS SUNP_17, 
     (SELECT DATA_YEAR2 AS DIVIDEND_PAYOUT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend payout') AS SUNP_18, 
     (SELECT DATA_YEAR2 AS AVG_MARKET_CAP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg Mkt Cap') AS SUNP_19, 
     (SELECT DATA_YEAR2 AS NO_OF_EMPLOYEES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='No. of employees') AS SUNP_20, 
     (SELECT DATA_YEAR2 AS TOTAL_WAGES_PER_SALARY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total wages/salary') AS SUNP_21, 
     (SELECT DATA_YEAR2 AS AVG_SALES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. sales/employee') AS SUNP_22, 
     (SELECT DATA_YEAR2 AS AVG_WAGES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. wages/employee') AS SUNP_23, 
     (SELECT DATA_YEAR2 AS AVG_NET_PROFIT_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. net profit/employee') AS SUNP_24;

INSERT INTO EQM_EQUITY_SHARE_DATA (HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE)
SELECT HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE
FROM (SELECT DATA_YEAR3 AS HIGH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='High') AS SUNP_1, 
     (SELECT DATA_YEAR3 AS LOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Low') AS SUNP_2, 
     (SELECT DATA_YEAR3 AS SALES_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales per share (Unadj.)') AS SUNP_3, 
     (SELECT DATA_YEAR3 AS EARNINGS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Earnings per share (Unadj.)') AS SUNP_4, 
     (SELECT DATA_YEAR3 AS DILUTED_EARNINGS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Diluted earnings per share') AS SUNP_5, 
     (SELECT DATA_YEAR3 AS CASH_FLOW_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Cash flow per share (Unadj.)') AS SUNP_6, 
     (SELECT DATA_YEAR3 AS DIVIDENDS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividends per share (Unadj.)') AS SUNP_7, 
     (SELECT DATA_YEAR3 AS ADJ_DIVIDENDS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. dividends per share') AS SUNP_8, 
     (SELECT DATA_YEAR3 AS DIVIDEND_YIELD_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend yield (eoy)') AS SUNP_9, 
     (SELECT DATA_YEAR3 AS BOOK_VALUE_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Book value per share (Unadj.)') AS SUNP_10, 
     (SELECT DATA_YEAR3 AS ADJ_BOOK_VALUE_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. book value per share') AS SUNP_11, 
     (SELECT DATA_YEAR3 AS SHARES_OUTSTANDING_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Shares outstanding (eoy)') AS SUNP_12, 
     (SELECT DATA_YEAR3 AS BONUS_RIGHTS_CONVERSIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='BRC') AS SUNP_13, 
     (SELECT DATA_YEAR3 AS PRICE_BY_SALES_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Sales ratio') AS SUNP_14, 
     (SELECT DATA_YEAR3 AS AVG_PE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg P/E ratio') AS SUNP_15, 
     (SELECT DATA_YEAR3 AS PRICE_BY_CASHFLOW_RATIO_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='P/CF ratio (eoy)') AS SUNP_16, 
     (SELECT DATA_YEAR3 AS PRICE_BY_BOOK_VALUE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Book Value ratio') AS SUNP_17, 
     (SELECT DATA_YEAR3 AS DIVIDEND_PAYOUT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend payout') AS SUNP_18, 
     (SELECT DATA_YEAR3 AS AVG_MARKET_CAP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg Mkt Cap') AS SUNP_19, 
     (SELECT DATA_YEAR3 AS NO_OF_EMPLOYEES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='No. of employees') AS SUNP_20, 
     (SELECT DATA_YEAR3 AS TOTAL_WAGES_PER_SALARY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total wages/salary') AS SUNP_21, 
     (SELECT DATA_YEAR3 AS AVG_SALES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. sales/employee') AS SUNP_22, 
     (SELECT DATA_YEAR3 AS AVG_WAGES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. wages/employee') AS SUNP_23, 
     (SELECT DATA_YEAR3 AS AVG_NET_PROFIT_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. net profit/employee') AS SUNP_24;


INSERT INTO EQM_EQUITY_SHARE_DATA (HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE)
SELECT HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE
FROM (SELECT DATA_YEAR4 AS HIGH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='High') AS SUNP_1, 
     (SELECT DATA_YEAR4 AS LOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Low') AS SUNP_2, 
     (SELECT DATA_YEAR4 AS SALES_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales per share (Unadj.)') AS SUNP_3, 
     (SELECT DATA_YEAR4 AS EARNINGS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Earnings per share (Unadj.)') AS SUNP_4, 
     (SELECT DATA_YEAR4 AS DILUTED_EARNINGS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Diluted earnings per share') AS SUNP_5, 
     (SELECT DATA_YEAR4 AS CASH_FLOW_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Cash flow per share (Unadj.)') AS SUNP_6, 
     (SELECT DATA_YEAR4 AS DIVIDENDS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividends per share (Unadj.)') AS SUNP_7, 
     (SELECT DATA_YEAR4 AS ADJ_DIVIDENDS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. dividends per share') AS SUNP_8, 
     (SELECT DATA_YEAR4 AS DIVIDEND_YIELD_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend yield (eoy)') AS SUNP_9, 
     (SELECT DATA_YEAR4 AS BOOK_VALUE_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Book value per share (Unadj.)') AS SUNP_10, 
     (SELECT DATA_YEAR4 AS ADJ_BOOK_VALUE_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. book value per share') AS SUNP_11, 
     (SELECT DATA_YEAR4 AS SHARES_OUTSTANDING_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Shares outstanding (eoy)') AS SUNP_12, 
     (SELECT DATA_YEAR4 AS BONUS_RIGHTS_CONVERSIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='BRC') AS SUNP_13, 
     (SELECT DATA_YEAR4 AS PRICE_BY_SALES_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Sales ratio') AS SUNP_14, 
     (SELECT DATA_YEAR4 AS AVG_PE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg P/E ratio') AS SUNP_15, 
     (SELECT DATA_YEAR4 AS PRICE_BY_CASHFLOW_RATIO_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='P/CF ratio (eoy)') AS SUNP_16, 
     (SELECT DATA_YEAR4 AS PRICE_BY_BOOK_VALUE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Book Value ratio') AS SUNP_17, 
     (SELECT DATA_YEAR4 AS DIVIDEND_PAYOUT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend payout') AS SUNP_18, 
     (SELECT DATA_YEAR4 AS AVG_MARKET_CAP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg Mkt Cap') AS SUNP_19, 
     (SELECT DATA_YEAR4 AS NO_OF_EMPLOYEES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='No. of employees') AS SUNP_20, 
     (SELECT DATA_YEAR4 AS TOTAL_WAGES_PER_SALARY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total wages/salary') AS SUNP_21, 
     (SELECT DATA_YEAR4 AS AVG_SALES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. sales/employee') AS SUNP_22, 
     (SELECT DATA_YEAR4 AS AVG_WAGES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. wages/employee') AS SUNP_23, 
     (SELECT DATA_YEAR4 AS AVG_NET_PROFIT_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. net profit/employee') AS SUNP_24;

INSERT INTO EQM_EQUITY_SHARE_DATA (HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE)
SELECT HIGH, LOW, SALES_PER_SHARE_UNADJ, EARNINGS_PER_SHARE_UNADJ, DILUTED_EARNINGS_PER_SHARE, CASH_FLOW_PER_SHARE_UNADJ, DIVIDENDS_PER_SHARE_UNADJ, ADJ_DIVIDENDS_PER_SHARE, DIVIDEND_YIELD_EOY, BOOK_VALUE_PER_SHARE_UNADJ, ADJ_BOOK_VALUE_PER_SHARE, SHARES_OUTSTANDING_EOY, BONUS_RIGHTS_CONVERSIONS, PRICE_BY_SALES_RATIO, AVG_PE_RATIO, PRICE_BY_CASHFLOW_RATIO_EOY, PRICE_BY_BOOK_VALUE_RATIO, DIVIDEND_PAYOUT, AVG_MARKET_CAP, NO_OF_EMPLOYEES, TOTAL_WAGES_PER_SALARY, AVG_SALES_PER_EMPLOYEE, AVG_WAGES_PER_EMPLOYEE, AVG_NET_PROFIT_PER_EMPLOYEE
FROM (SELECT DATA_YEAR5 AS HIGH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='High') AS SUNP_1, 
     (SELECT DATA_YEAR5 AS LOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Low') AS SUNP_2, 
     (SELECT DATA_YEAR5 AS SALES_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales per share (Unadj.)') AS SUNP_3, 
     (SELECT DATA_YEAR5 AS EARNINGS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Earnings per share (Unadj.)') AS SUNP_4, 
     (SELECT DATA_YEAR5 AS DILUTED_EARNINGS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Diluted earnings per share') AS SUNP_5, 
     (SELECT DATA_YEAR5 AS CASH_FLOW_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Cash flow per share (Unadj.)') AS SUNP_6, 
     (SELECT DATA_YEAR5 AS DIVIDENDS_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividends per share (Unadj.)') AS SUNP_7, 
     (SELECT DATA_YEAR5 AS ADJ_DIVIDENDS_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. dividends per share') AS SUNP_8, 
     (SELECT DATA_YEAR5 AS DIVIDEND_YIELD_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend yield (eoy)') AS SUNP_9, 
     (SELECT DATA_YEAR5 AS BOOK_VALUE_PER_SHARE_UNADJ FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Book value per share (Unadj.)') AS SUNP_10, 
     (SELECT DATA_YEAR5 AS ADJ_BOOK_VALUE_PER_SHARE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Adj. book value per share') AS SUNP_11, 
     (SELECT DATA_YEAR5 AS SHARES_OUTSTANDING_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Shares outstanding (eoy)') AS SUNP_12, 
     (SELECT DATA_YEAR5 AS BONUS_RIGHTS_CONVERSIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='BRC') AS SUNP_13, 
     (SELECT DATA_YEAR5 AS PRICE_BY_SALES_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Sales ratio') AS SUNP_14, 
     (SELECT DATA_YEAR5 AS AVG_PE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg P/E ratio') AS SUNP_15, 
     (SELECT DATA_YEAR5 AS PRICE_BY_CASHFLOW_RATIO_EOY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='P/CF ratio (eoy)') AS SUNP_16, 
     (SELECT DATA_YEAR5 AS PRICE_BY_BOOK_VALUE_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Price / Book Value ratio') AS SUNP_17, 
     (SELECT DATA_YEAR5 AS DIVIDEND_PAYOUT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Dividend payout') AS SUNP_18, 
     (SELECT DATA_YEAR5 AS AVG_MARKET_CAP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg Mkt Cap') AS SUNP_19, 
     (SELECT DATA_YEAR5 AS NO_OF_EMPLOYEES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='No. of employees') AS SUNP_20, 
     (SELECT DATA_YEAR5 AS TOTAL_WAGES_PER_SALARY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total wages/salary') AS SUNP_21, 
     (SELECT DATA_YEAR5 AS AVG_SALES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. sales/employee') AS SUNP_22, 
     (SELECT DATA_YEAR5 AS AVG_WAGES_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. wages/employee') AS SUNP_23, 
     (SELECT DATA_YEAR5 AS AVG_NET_PROFIT_PER_EMPLOYEE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Avg. net profit/employee') AS SUNP_24;	 
	 
	 

-- ****************************************************************************
-- Import the BALANCESHEET DATA
-- ****************************************************************************
DELETE FROM TMP_EQM_5YEAR_DATA;

.import ../temp/data_SUNP_BS TMP_EQM_5YEAR_DATA

INSERT INTO EQM_BALANCE_SHEET_DATA (CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX)
  SELECT CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX
FROM (SELECT DATA_YEAR1 AS CURRENT_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current assets') AS SUNP_1, 
     (SELECT DATA_YEAR1 AS CURRENT_LIABILITIES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current liabilities') AS SUNP_2, 
     (SELECT DATA_YEAR1 AS NET_WORKING_CAP_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net working cap to sales') AS SUNP_3, 
     (SELECT DATA_YEAR1 AS CURRENT_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current ratio') AS SUNP_4, 
     (SELECT DATA_YEAR1 AS INVENTORY_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Inventory Days') AS SUNP_5, 
     (SELECT DATA_YEAR1 AS DEBTORS_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debtors Days') AS SUNP_6, 
     (SELECT DATA_YEAR1 AS NET_FIXED_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fixed assets') AS SUNP_7, 
     (SELECT DATA_YEAR1 AS SHARE_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Share capital') AS SUNP_8, 
     (SELECT DATA_YEAR1 AS FREE_RESERVES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Free reserves') AS SUNP_9, 
     (SELECT DATA_YEAR1 AS NET_WORTH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net worth') AS SUNP_10, 
     (SELECT DATA_YEAR1 AS LONG_TERM_DEBT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Long term debt') AS SUNP_11, 
     (SELECT DATA_YEAR1 AS TOTAL_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total assets') AS SUNP_12, 
     (SELECT DATA_YEAR1 AS INTEREST_COVERAGE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest coverage') AS SUNP_13, 
     (SELECT DATA_YEAR1 AS DEBT_TO_EQUITY_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debt to equity ratio') AS SUNP_14, 
     (SELECT DATA_YEAR1 AS SALES_TO_ASSETS_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales to assets ratio') AS SUNP_15, 
     (SELECT DATA_YEAR1 AS RETURN_ON_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on assets') AS SUNP_16, 
     (SELECT DATA_YEAR1 AS RETURN_ON_EQUITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on equity') AS SUNP_17, 
     (SELECT DATA_YEAR1 AS RETURN_ON_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on capital') AS SUNP_18, 
     (SELECT DATA_YEAR1 AS EXPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports to sales') AS SUNP_19, 
     (SELECT DATA_YEAR1 AS IMPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports to sales') AS SUNP_20, 
     (SELECT DATA_YEAR1 AS EXPORTS_FOB FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports (fob)') AS SUNP_21, 
     (SELECT DATA_YEAR1 AS IMPORTS_CIF FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports (cif)') AS SUNP_22, 
     (SELECT DATA_YEAR1 AS FX_INFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx inflow') AS SUNP_23, 
     (SELECT DATA_YEAR1 AS FX_OUTFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx outflow') AS SUNP_24, 
     (SELECT DATA_YEAR1 AS NET_FX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fx') AS SUNP_25;


INSERT INTO EQM_BALANCE_SHEET_DATA (CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX)
  SELECT CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX
FROM (SELECT DATA_YEAR2 AS CURRENT_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current assets') AS SUNP_1, 
     (SELECT DATA_YEAR2 AS CURRENT_LIABILITIES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current liabilities') AS SUNP_2, 
     (SELECT DATA_YEAR2 AS NET_WORKING_CAP_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net working cap to sales') AS SUNP_3, 
     (SELECT DATA_YEAR2 AS CURRENT_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current ratio') AS SUNP_4, 
     (SELECT DATA_YEAR2 AS INVENTORY_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Inventory Days') AS SUNP_5, 
     (SELECT DATA_YEAR2 AS DEBTORS_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debtors Days') AS SUNP_6, 
     (SELECT DATA_YEAR2 AS NET_FIXED_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fixed assets') AS SUNP_7, 
     (SELECT DATA_YEAR2 AS SHARE_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Share capital') AS SUNP_8, 
     (SELECT DATA_YEAR2 AS FREE_RESERVES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Free reserves') AS SUNP_9, 
     (SELECT DATA_YEAR2 AS NET_WORTH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net worth') AS SUNP_10, 
     (SELECT DATA_YEAR2 AS LONG_TERM_DEBT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Long term debt') AS SUNP_11, 
     (SELECT DATA_YEAR2 AS TOTAL_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total assets') AS SUNP_12, 
     (SELECT DATA_YEAR2 AS INTEREST_COVERAGE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest coverage') AS SUNP_13, 
     (SELECT DATA_YEAR2 AS DEBT_TO_EQUITY_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debt to equity ratio') AS SUNP_14, 
     (SELECT DATA_YEAR2 AS SALES_TO_ASSETS_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales to assets ratio') AS SUNP_15, 
     (SELECT DATA_YEAR2 AS RETURN_ON_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on assets') AS SUNP_16, 
     (SELECT DATA_YEAR2 AS RETURN_ON_EQUITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on equity') AS SUNP_17, 
     (SELECT DATA_YEAR2 AS RETURN_ON_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on capital') AS SUNP_18, 
     (SELECT DATA_YEAR2 AS EXPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports to sales') AS SUNP_19, 
     (SELECT DATA_YEAR2 AS IMPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports to sales') AS SUNP_20, 
     (SELECT DATA_YEAR2 AS EXPORTS_FOB FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports (fob)') AS SUNP_21, 
     (SELECT DATA_YEAR2 AS IMPORTS_CIF FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports (cif)') AS SUNP_22, 
     (SELECT DATA_YEAR2 AS FX_INFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx inflow') AS SUNP_23, 
     (SELECT DATA_YEAR2 AS FX_OUTFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx outflow') AS SUNP_24, 
     (SELECT DATA_YEAR2 AS NET_FX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fx') AS SUNP_25;

	 
	 
INSERT INTO EQM_BALANCE_SHEET_DATA (CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX)
  SELECT CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX
FROM (SELECT DATA_YEAR3 AS CURRENT_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current assets') AS SUNP_1, 
     (SELECT DATA_YEAR3 AS CURRENT_LIABILITIES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current liabilities') AS SUNP_2, 
     (SELECT DATA_YEAR3 AS NET_WORKING_CAP_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net working cap to sales') AS SUNP_3, 
     (SELECT DATA_YEAR3 AS CURRENT_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current ratio') AS SUNP_4, 
     (SELECT DATA_YEAR3 AS INVENTORY_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Inventory Days') AS SUNP_5, 
     (SELECT DATA_YEAR3 AS DEBTORS_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debtors Days') AS SUNP_6, 
     (SELECT DATA_YEAR3 AS NET_FIXED_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fixed assets') AS SUNP_7, 
     (SELECT DATA_YEAR3 AS SHARE_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Share capital') AS SUNP_8, 
     (SELECT DATA_YEAR3 AS FREE_RESERVES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Free reserves') AS SUNP_9, 
     (SELECT DATA_YEAR3 AS NET_WORTH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net worth') AS SUNP_10, 
     (SELECT DATA_YEAR3 AS LONG_TERM_DEBT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Long term debt') AS SUNP_11, 
     (SELECT DATA_YEAR3 AS TOTAL_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total assets') AS SUNP_12, 
     (SELECT DATA_YEAR3 AS INTEREST_COVERAGE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest coverage') AS SUNP_13, 
     (SELECT DATA_YEAR3 AS DEBT_TO_EQUITY_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debt to equity ratio') AS SUNP_14, 
     (SELECT DATA_YEAR3 AS SALES_TO_ASSETS_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales to assets ratio') AS SUNP_15, 
     (SELECT DATA_YEAR3 AS RETURN_ON_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on assets') AS SUNP_16, 
     (SELECT DATA_YEAR3 AS RETURN_ON_EQUITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on equity') AS SUNP_17, 
     (SELECT DATA_YEAR3 AS RETURN_ON_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on capital') AS SUNP_18, 
     (SELECT DATA_YEAR3 AS EXPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports to sales') AS SUNP_19, 
     (SELECT DATA_YEAR3 AS IMPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports to sales') AS SUNP_20, 
     (SELECT DATA_YEAR3 AS EXPORTS_FOB FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports (fob)') AS SUNP_21, 
     (SELECT DATA_YEAR3 AS IMPORTS_CIF FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports (cif)') AS SUNP_22, 
     (SELECT DATA_YEAR3 AS FX_INFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx inflow') AS SUNP_23, 
     (SELECT DATA_YEAR3 AS FX_OUTFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx outflow') AS SUNP_24, 
     (SELECT DATA_YEAR3 AS NET_FX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fx') AS SUNP_25;



INSERT INTO EQM_BALANCE_SHEET_DATA (CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX)
  SELECT CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX
FROM (SELECT DATA_YEAR4 AS CURRENT_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current assets') AS SUNP_1, 
     (SELECT DATA_YEAR4 AS CURRENT_LIABILITIES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current liabilities') AS SUNP_2, 
     (SELECT DATA_YEAR4 AS NET_WORKING_CAP_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net working cap to sales') AS SUNP_3, 
     (SELECT DATA_YEAR4 AS CURRENT_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current ratio') AS SUNP_4, 
     (SELECT DATA_YEAR4 AS INVENTORY_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Inventory Days') AS SUNP_5, 
     (SELECT DATA_YEAR4 AS DEBTORS_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debtors Days') AS SUNP_6, 
     (SELECT DATA_YEAR4 AS NET_FIXED_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fixed assets') AS SUNP_7, 
     (SELECT DATA_YEAR4 AS SHARE_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Share capital') AS SUNP_8, 
     (SELECT DATA_YEAR4 AS FREE_RESERVES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Free reserves') AS SUNP_9, 
     (SELECT DATA_YEAR4 AS NET_WORTH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net worth') AS SUNP_10, 
     (SELECT DATA_YEAR4 AS LONG_TERM_DEBT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Long term debt') AS SUNP_11, 
     (SELECT DATA_YEAR4 AS TOTAL_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total assets') AS SUNP_12, 
     (SELECT DATA_YEAR4 AS INTEREST_COVERAGE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest coverage') AS SUNP_13, 
     (SELECT DATA_YEAR4 AS DEBT_TO_EQUITY_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debt to equity ratio') AS SUNP_14, 
     (SELECT DATA_YEAR4 AS SALES_TO_ASSETS_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales to assets ratio') AS SUNP_15, 
     (SELECT DATA_YEAR4 AS RETURN_ON_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on assets') AS SUNP_16, 
     (SELECT DATA_YEAR4 AS RETURN_ON_EQUITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on equity') AS SUNP_17, 
     (SELECT DATA_YEAR4 AS RETURN_ON_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on capital') AS SUNP_18, 
     (SELECT DATA_YEAR4 AS EXPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports to sales') AS SUNP_19, 
     (SELECT DATA_YEAR4 AS IMPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports to sales') AS SUNP_20, 
     (SELECT DATA_YEAR4 AS EXPORTS_FOB FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports (fob)') AS SUNP_21, 
     (SELECT DATA_YEAR4 AS IMPORTS_CIF FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports (cif)') AS SUNP_22, 
     (SELECT DATA_YEAR4 AS FX_INFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx inflow') AS SUNP_23, 
     (SELECT DATA_YEAR4 AS FX_OUTFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx outflow') AS SUNP_24, 
     (SELECT DATA_YEAR4 AS NET_FX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fx') AS SUNP_25;



INSERT INTO EQM_BALANCE_SHEET_DATA (CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX)
  SELECT CURRENT_ASSETS, CURRENT_LIABILITIES, NET_WORKING_CAP_TO_SALES, CURRENT_RATIO, INVENTORY_DAYS, DEBTORS_DAYS, NET_FIXED_ASSETS, SHARE_CAPITAL, FREE_RESERVES, NET_WORTH, LONG_TERM_DEBT, TOTAL_ASSETS, INTEREST_COVERAGE, DEBT_TO_EQUITY_RATIO, SALES_TO_ASSETS_RATIO, RETURN_ON_ASSETS, RETURN_ON_EQUITY, RETURN_ON_CAPITAL, EXPORTS_TO_SALES, IMPORTS_TO_SALES, EXPORTS_FOB, IMPORTS_CIF, FX_INFLOW, FX_OUTFLOW, NET_FX
FROM (SELECT DATA_YEAR5 AS CURRENT_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current assets') AS SUNP_1, 
     (SELECT DATA_YEAR5 AS CURRENT_LIABILITIES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current liabilities') AS SUNP_2, 
     (SELECT DATA_YEAR5 AS NET_WORKING_CAP_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net working cap to sales') AS SUNP_3, 
     (SELECT DATA_YEAR5 AS CURRENT_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Current ratio') AS SUNP_4, 
     (SELECT DATA_YEAR5 AS INVENTORY_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Inventory Days') AS SUNP_5, 
     (SELECT DATA_YEAR5 AS DEBTORS_DAYS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debtors Days') AS SUNP_6, 
     (SELECT DATA_YEAR5 AS NET_FIXED_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fixed assets') AS SUNP_7, 
     (SELECT DATA_YEAR5 AS SHARE_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Share capital') AS SUNP_8, 
     (SELECT DATA_YEAR5 AS FREE_RESERVES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Free reserves') AS SUNP_9, 
     (SELECT DATA_YEAR5 AS NET_WORTH FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net worth') AS SUNP_10, 
     (SELECT DATA_YEAR5 AS LONG_TERM_DEBT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Long term debt') AS SUNP_11, 
     (SELECT DATA_YEAR5 AS TOTAL_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total assets') AS SUNP_12, 
     (SELECT DATA_YEAR5 AS INTEREST_COVERAGE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest coverage') AS SUNP_13, 
     (SELECT DATA_YEAR5 AS DEBT_TO_EQUITY_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Debt to equity ratio') AS SUNP_14, 
     (SELECT DATA_YEAR5 AS SALES_TO_ASSETS_RATIO FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Sales to assets ratio') AS SUNP_15, 
     (SELECT DATA_YEAR5 AS RETURN_ON_ASSETS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on assets') AS SUNP_16, 
     (SELECT DATA_YEAR5 AS RETURN_ON_EQUITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on equity') AS SUNP_17, 
     (SELECT DATA_YEAR5 AS RETURN_ON_CAPITAL FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Return on capital') AS SUNP_18, 
     (SELECT DATA_YEAR5 AS EXPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports to sales') AS SUNP_19, 
     (SELECT DATA_YEAR5 AS IMPORTS_TO_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports to sales') AS SUNP_20, 
     (SELECT DATA_YEAR5 AS EXPORTS_FOB FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Exports (fob)') AS SUNP_21, 
     (SELECT DATA_YEAR5 AS IMPORTS_CIF FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Imports (cif)') AS SUNP_22, 
     (SELECT DATA_YEAR5 AS FX_INFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx inflow') AS SUNP_23, 
     (SELECT DATA_YEAR5 AS FX_OUTFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Fx outflow') AS SUNP_24, 
     (SELECT DATA_YEAR5 AS NET_FX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net fx') AS SUNP_25;


	 
	 
	 
	 
	 
	 
-- ****************************************************************************
-- Import the INCOME DATA
-- ****************************************************************************
DELETE FROM TMP_EQM_5YEAR_DATA;

.import ../temp/data_SUNP_ID TMP_EQM_5YEAR_DATA

INSERT INTO EQM_INCOME_DATA (NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN)
SELECT NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN
  FROM (SELECT DATA_YEAR1 AS NET_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Sales') AS SUNP_1, 
       (SELECT DATA_YEAR1 AS OTHER_INCOME FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Other income') AS SUNP_2, 
       (SELECT DATA_YEAR1 AS TOTAL_REVENUES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total revenues') AS SUNP_3, 
       (SELECT DATA_YEAR1 AS GROSS_PROFIT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit') AS SUNP_4, 
       (SELECT DATA_YEAR1 AS DEPRECIATION FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Depreciation') AS SUNP_5, 
       (SELECT DATA_YEAR1 AS INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest') AS SUNP_6, 
       (SELECT DATA_YEAR1 AS PROFIT_BEFORE_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit before tax') AS SUNP_7, 
       (SELECT DATA_YEAR1 AS MINORITY_INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Minority Interest') AS SUNP_8, 
       (SELECT DATA_YEAR1 AS PRIOR_PERIOD_ITEMS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Prior Period Items') AS SUNP_9, 
       (SELECT DATA_YEAR1 AS EXTRAORDINARY_INC_EXP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Extraordinary Inc (Exp)') AS SUNP_10, 
       (SELECT DATA_YEAR1 AS TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Tax') AS SUNP_11, 
       (SELECT DATA_YEAR1 AS PROFIT_AFTER_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit after tax') AS SUNP_12, 
       (SELECT DATA_YEAR1 AS GROSS_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit margin') AS SUNP_13, 
       (SELECT DATA_YEAR1 AS EFFECTIVE_TAX_RATE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Effective tax rate') AS SUNP_14, 
       (SELECT DATA_YEAR1 AS NET_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net profit margin') AS SUNP_15;


INSERT INTO EQM_INCOME_DATA (NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN)
SELECT NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN
  FROM (SELECT DATA_YEAR2 AS NET_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Sales') AS SUNP_1, 
       (SELECT DATA_YEAR2 AS OTHER_INCOME FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Other income') AS SUNP_2, 
       (SELECT DATA_YEAR2 AS TOTAL_REVENUES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total revenues') AS SUNP_3, 
       (SELECT DATA_YEAR2 AS GROSS_PROFIT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit') AS SUNP_4, 
       (SELECT DATA_YEAR2 AS DEPRECIATION FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Depreciation') AS SUNP_5, 
       (SELECT DATA_YEAR2 AS INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest') AS SUNP_6, 
       (SELECT DATA_YEAR2 AS PROFIT_BEFORE_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit before tax') AS SUNP_7, 
       (SELECT DATA_YEAR2 AS MINORITY_INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Minority Interest') AS SUNP_8, 
       (SELECT DATA_YEAR2 AS PRIOR_PERIOD_ITEMS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Prior Period Items') AS SUNP_9, 
       (SELECT DATA_YEAR2 AS EXTRAORDINARY_INC_EXP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Extraordinary Inc (Exp)') AS SUNP_10, 
       (SELECT DATA_YEAR2 AS TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Tax') AS SUNP_11, 
       (SELECT DATA_YEAR2 AS PROFIT_AFTER_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit after tax') AS SUNP_12, 
       (SELECT DATA_YEAR2 AS GROSS_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit margin') AS SUNP_13, 
       (SELECT DATA_YEAR2 AS EFFECTIVE_TAX_RATE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Effective tax rate') AS SUNP_14, 
       (SELECT DATA_YEAR2 AS NET_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net profit margin') AS SUNP_15;


INSERT INTO EQM_INCOME_DATA (NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN)
SELECT NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN
  FROM (SELECT DATA_YEAR3 AS NET_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Sales') AS SUNP_1, 
       (SELECT DATA_YEAR3 AS OTHER_INCOME FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Other income') AS SUNP_2, 
       (SELECT DATA_YEAR3 AS TOTAL_REVENUES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total revenues') AS SUNP_3, 
       (SELECT DATA_YEAR3 AS GROSS_PROFIT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit') AS SUNP_4, 
       (SELECT DATA_YEAR3 AS DEPRECIATION FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Depreciation') AS SUNP_5, 
       (SELECT DATA_YEAR3 AS INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest') AS SUNP_6, 
       (SELECT DATA_YEAR3 AS PROFIT_BEFORE_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit before tax') AS SUNP_7, 
       (SELECT DATA_YEAR3 AS MINORITY_INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Minority Interest') AS SUNP_8, 
       (SELECT DATA_YEAR3 AS PRIOR_PERIOD_ITEMS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Prior Period Items') AS SUNP_9, 
       (SELECT DATA_YEAR3 AS EXTRAORDINARY_INC_EXP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Extraordinary Inc (Exp)') AS SUNP_10, 
       (SELECT DATA_YEAR3 AS TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Tax') AS SUNP_11, 
       (SELECT DATA_YEAR3 AS PROFIT_AFTER_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit after tax') AS SUNP_12, 
       (SELECT DATA_YEAR3 AS GROSS_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit margin') AS SUNP_13, 
       (SELECT DATA_YEAR3 AS EFFECTIVE_TAX_RATE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Effective tax rate') AS SUNP_14, 
       (SELECT DATA_YEAR3 AS NET_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net profit margin') AS SUNP_15;



INSERT INTO EQM_INCOME_DATA (NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN)
SELECT NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN
  FROM (SELECT DATA_YEAR4 AS NET_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Sales') AS SUNP_1, 
       (SELECT DATA_YEAR4 AS OTHER_INCOME FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Other income') AS SUNP_2, 
       (SELECT DATA_YEAR4 AS TOTAL_REVENUES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total revenues') AS SUNP_3, 
       (SELECT DATA_YEAR4 AS GROSS_PROFIT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit') AS SUNP_4, 
       (SELECT DATA_YEAR4 AS DEPRECIATION FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Depreciation') AS SUNP_5, 
       (SELECT DATA_YEAR4 AS INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest') AS SUNP_6, 
       (SELECT DATA_YEAR4 AS PROFIT_BEFORE_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit before tax') AS SUNP_7, 
       (SELECT DATA_YEAR4 AS MINORITY_INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Minority Interest') AS SUNP_8, 
       (SELECT DATA_YEAR4 AS PRIOR_PERIOD_ITEMS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Prior Period Items') AS SUNP_9, 
       (SELECT DATA_YEAR4 AS EXTRAORDINARY_INC_EXP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Extraordinary Inc (Exp)') AS SUNP_10, 
       (SELECT DATA_YEAR4 AS TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Tax') AS SUNP_11, 
       (SELECT DATA_YEAR4 AS PROFIT_AFTER_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit after tax') AS SUNP_12, 
       (SELECT DATA_YEAR4 AS GROSS_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit margin') AS SUNP_13, 
       (SELECT DATA_YEAR4 AS EFFECTIVE_TAX_RATE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Effective tax rate') AS SUNP_14, 
       (SELECT DATA_YEAR4 AS NET_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net profit margin') AS SUNP_15;



INSERT INTO EQM_INCOME_DATA (NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN)
SELECT NET_SALES, OTHER_INCOME, TOTAL_REVENUES, GROSS_PROFIT, DEPRECIATION, INTEREST, PROFIT_BEFORE_TAX, MINORITY_INTEREST, PRIOR_PERIOD_ITEMS, EXTRAORDINARY_INC_EXP, TAX, PROFIT_AFTER_TAX, GROSS_PROFIT_MARGIN, EFFECTIVE_TAX_RATE, NET_PROFIT_MARGIN
  FROM (SELECT DATA_YEAR5 AS NET_SALES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Sales') AS SUNP_1, 
       (SELECT DATA_YEAR5 AS OTHER_INCOME FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Other income') AS SUNP_2, 
       (SELECT DATA_YEAR5 AS TOTAL_REVENUES FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Total revenues') AS SUNP_3, 
       (SELECT DATA_YEAR5 AS GROSS_PROFIT FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit') AS SUNP_4, 
       (SELECT DATA_YEAR5 AS DEPRECIATION FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Depreciation') AS SUNP_5, 
       (SELECT DATA_YEAR5 AS INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Interest') AS SUNP_6, 
       (SELECT DATA_YEAR5 AS PROFIT_BEFORE_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit before tax') AS SUNP_7, 
       (SELECT DATA_YEAR5 AS MINORITY_INTEREST FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Minority Interest') AS SUNP_8, 
       (SELECT DATA_YEAR5 AS PRIOR_PERIOD_ITEMS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Prior Period Items') AS SUNP_9, 
       (SELECT DATA_YEAR5 AS EXTRAORDINARY_INC_EXP FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Extraordinary Inc (Exp)') AS SUNP_10, 
       (SELECT DATA_YEAR5 AS TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Tax') AS SUNP_11, 
       (SELECT DATA_YEAR5 AS PROFIT_AFTER_TAX FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Profit after tax') AS SUNP_12, 
       (SELECT DATA_YEAR5 AS GROSS_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Gross profit margin') AS SUNP_13, 
       (SELECT DATA_YEAR5 AS EFFECTIVE_TAX_RATE FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Effective tax rate') AS SUNP_14, 
       (SELECT DATA_YEAR5 AS NET_PROFIT_MARGIN FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net profit margin') AS SUNP_15;
	   

	   
	   
	   
-- ****************************************************************************
-- Import the CASHFLOW DATA
-- ****************************************************************************
DELETE FROM TMP_EQM_5YEAR_DATA;

.import ../temp/data_SUNP_CF TMP_EQM_5YEAR_DATA
INSERT INTO EQM_CASHFLOW (FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW)
SELECT FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW 
  FROM (SELECT DATA_YEAR1 AS FROM_OPERATIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Operations') AS SUNP_1, 
       (SELECT DATA_YEAR1 AS FROM_INVESTMENTS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Investments') AS SUNP_2, 
       (SELECT DATA_YEAR1 AS FROM_FINANCIAL_ACTIVITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Financial Activity') AS SUNP_3, 
       (SELECT DATA_YEAR1 AS NET_CASHFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Cashflow') AS SUNP_4;


INSERT INTO EQM_CASHFLOW (FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW)
SELECT FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW 
  FROM (SELECT DATA_YEAR2 AS FROM_OPERATIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Operations') AS SUNP_1, 
       (SELECT DATA_YEAR2 AS FROM_INVESTMENTS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Investments') AS SUNP_2, 
       (SELECT DATA_YEAR2 AS FROM_FINANCIAL_ACTIVITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Financial Activity') AS SUNP_3, 
       (SELECT DATA_YEAR2 AS NET_CASHFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Cashflow') AS SUNP_4;


INSERT INTO EQM_CASHFLOW (FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW)
SELECT FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW 
  FROM (SELECT DATA_YEAR3 AS FROM_OPERATIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Operations') AS SUNP_1, 
       (SELECT DATA_YEAR3 AS FROM_INVESTMENTS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Investments') AS SUNP_2, 
       (SELECT DATA_YEAR3 AS FROM_FINANCIAL_ACTIVITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Financial Activity') AS SUNP_3, 
       (SELECT DATA_YEAR3 AS NET_CASHFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Cashflow') AS SUNP_4;


INSERT INTO EQM_CASHFLOW (FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW)
SELECT FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW 
  FROM (SELECT DATA_YEAR4 AS FROM_OPERATIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Operations') AS SUNP_1, 
       (SELECT DATA_YEAR4 AS FROM_INVESTMENTS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Investments') AS SUNP_2, 
       (SELECT DATA_YEAR4 AS FROM_FINANCIAL_ACTIVITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Financial Activity') AS SUNP_3, 
       (SELECT DATA_YEAR4 AS NET_CASHFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Cashflow') AS SUNP_4;


INSERT INTO EQM_CASHFLOW (FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW)
SELECT FROM_OPERATIONS, FROM_INVESTMENTS, FROM_FINANCIAL_ACTIVITY, NET_CASHFLOW 
  FROM (SELECT DATA_YEAR5 AS FROM_OPERATIONS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Operations') AS SUNP_1, 
       (SELECT DATA_YEAR5 AS FROM_INVESTMENTS FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Investments') AS SUNP_2, 
       (SELECT DATA_YEAR5 AS FROM_FINANCIAL_ACTIVITY FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='From Financial Activity') AS SUNP_3, 
       (SELECT DATA_YEAR5 AS NET_CASHFLOW FROM  TMP_EQM_5YEAR_DATA WHERE DATA_TYPE='Net Cashflow') AS SUNP_4;

	   






-- ****************************************************************************
-- Import the SHAREHIOLDING DATA
-- ****************************************************************************
 DELETE FROM TMP_EQM_SHAREHOLDING;

.import ../temp/data_SUNP_SP TMP_EQM_SHAREHOLDING

INSERT INTO EQM_SHAREHOLDING 
       (INDIAN_PROMOTERS, FOREIGN_COLLABORATORS, INDIAN_INST_MUT_FUND, FIIS, ADR_GDR, FREE_FLOAT, SHAREHOLDERS, PLEDGED_PROMOTER_HOLDING)
 SELECT INDIAN_PROMOTERS, FOREIGN_COLLABORATORS, INDIAN_INST_MUT_FUND, FIIS, ADR_GDR, FREE_FLOAT, SHAREHOLDERS, PLEDGED_PROMOTER_HOLDING
   FROM TMP_EQM_SHAREHOLDING; 

   
